trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Step 1: Cloning repository"
        echo "Step 2: Compiling source code"
        echo "Step 3: Running unit tests"
      displayName: 'Build and Test'

- stage: Deploy
  displayName: 'Deploy Stage'
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - script: |
        echo "Step 1: Deploying to staging environment"
        echo "Step 2: Running integration tests"
        echo "Step 3: Deploying to production"
      displayName: 'Deploy to Production'
